### ISSUE TITLE
Normalize NLD to discrete states only

### ISSUE THREAD

**Issue by vetlewi** [oslocyclotronlab/ompy#135]
There might be cases where normalizing the NLD to discrete states are sufficient.

**Comment by fzeiser** [comment]
The *cleanest* way of doing this is to adopt the likelihood, eg. remove 
`err_nldSn = ((nldSn[0] - nldSn_model)/nldSn[1])**2` in 
https://github.com/oslocyclotronlab/ompy/blob/d21326012dc95cffb1b83ae947739e42aefd5b27/ompy/normalizer_nld.py#L503-L508

You could perfrom something similar in normalizer_simulan:
- the likelihood for the nld normalization is already taken over from `NormalizerNLD`, so it is sufficient to change it only once
- remove the likelihood pat due to Gg
- potentially add some comparison of the gsf to the tail of the GDR

A quick and dirty fix (only for short testing) would be to set the uncertainty of D0 (and Gg) to ridiculous values, like 1000 times the nominal value.

**Comment by fzeiser** [comment]
Erlend considered previously whether to create a more abstract class to comfort different types of normalizations, but we decided that there are too many different cases. And we feel that it it easy enough to change the likelihood function. So we will leave it like this.

If you plan o work on this, could you post an example of the result / branch instead? I think this will be just as easy to work with, if people can just see how to adopt the code.

**Comment by vetlewi** [comment]
> The _cleanest_ way of doing this is to adopt the likelihood, eg. remove
> `err_nldSn = ((nldSn[0] - nldSn_model)/nldSn[1])**2` in
> 
> https://github.com/oslocyclotronlab/ompy/blob/d21326012dc95cffb1b83ae947739e42aefd5b27/ompy/normalizer_nld.py#L503-L508
> 
> You could perfrom something similar in normalizer_simulan:
> 
> * the likelihood for the nld normalization is already taken over from `NormalizerNLD`, so it is sufficient to change it only once
> * remove the likelihood pat due to Gg
> * potentially add some comparison of the gsf to the tail of the GDR
> 
> A quick and dirty fix (only for short testing) would be to set the uncertainty of D0 (and Gg) to ridiculous values, like 1000 times the nominal value.

This worked great!

**Comment by fzeiser** [comment]
I will close the issue for now (open it if there is more questions), but you're very welcome to post a link the to child class with an adopted `lnlike` method.
