### ISSUE TITLE
Error in normalization of NLD

### ISSUE THREAD

**Issue by vetlewi** [oslocyclotronlab/ompy#90]
I've found a major bug in the normalization of the NLD. This might be related to issue #89, but I'm not sure.  
Anyways:  
When calculating the NLD at Sn the NormalizerNLD used the following code:
https://github.com/oslocyclotronlab/ompy/blob/9ac0f5e24b2bd966dcff399cc1c245ae74d9cbc8/ompy/normalizer_nld.py#L674-L685

which at first glance looks to be correct, however there is a factor 2 missing to account for the different parities. The correct should be
```python
NLD = 2 / (summe * D0 * 1e-6)
```

**Comment by fzeiser** [comment]
Maybe you're right, but I think you're not. I had the issue when I wrote up the code, but I need to go through it again ;P.

I think, what I coded up is correct if *if* eq. (19) in Larsen2011 was correct. If the equation was the following

`1/D₀ = 1/2 (g(J+1/2, pi) + g(J-1/2, pi) )` instead of 
`1/D₀ = 1/2 (g(J+1/2) + g(J-1/2) )` . <- version in the article

We would need to implement your revision if the equation in the article was wrong, do you agree?

However, I'm not totally sure that this equation is wrong. I think the *correct* equation says that the nld of accessible levels, `1/D₀`, is the sum of the accessible spins, so `g(J+1/2, pi) + g(J-1/2, pi)` if `J>0`, and `g(J+1/2, pi)` if `J=0`. However, as we normalize `g(J)` to one and assume equiparity, this is equal to `1/2 [ g(J+1/2) + g(J-1/2) ]`, isn't it? Which is the equation in the article and what I coded up.

> This might be related to issue #89, but I'm not sure.

No

**Comment by vetlewi** [comment]
Well, the version in OMpy gives half the NLD as D2rho

**Comment by fzeiser** [comment]
That is good to know. I assume you are right then, but I would like to go through the derivations once again before claiming that d2rho or ompy it correct. We should at least know why we*re wrong. So what is wrong in the derivation as outlines above? Let's try to drag Ann-Cecilie in there, too.

**Comment by vetlewi** [comment]
> Well, the version in OMpy gives half the NLD as D2rho. g(J,pi) = g(J)/2. 1/D0 = rho(Sn)_(g(J+1/2,pi) + g(J-1/2,pi)) = rho(Sn)_(g(J+1/2) + g(J-1/2))/2. rho(Sn) = 2/D0 * 1/(g(J+1/2) + g(J-1/2))

Let me clean this up quickly

**Comment by fzeiser** [comment]
I didn't see your comment before writing this ...

**Comment by fzeiser** [comment]
Could it be that only the first part is wrong? 
https://github.com/oslocyclotronlab/ompy/blob/9ac0f5e24b2bd966dcff399cc1c245ae74d9cbc8/ompy/normalizer_nld.py#L679-L680

Here we already have a factor of two:
https://github.com/oslocyclotronlab/ompy/blob/9ac0f5e24b2bd966dcff399cc1c245ae74d9cbc8/ompy/normalizer_nld.py#L681-L682

**Comment by vetlewi** [comment]
Equiparity: 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/5293376/70220632-3060f980-1747-11ea-9137-7b8f182a8f77.png">

s-wave spacing:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/5293376/70220819-7e75fd00-1747-11ea-89f5-7167bb435f57.png">

and the NLD at Sn:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/5293376/70220884-9baacb80-1747-11ea-8d96-958a138dbcfb.png">

Of coarse the J-1/2 term vanishes if J = 0

**Comment by vetlewi** [comment]
> Could it be that only the first part is wrong?
> 
> https://github.com/oslocyclotronlab/ompy/blob/9ac0f5e24b2bd966dcff399cc1c245ae74d9cbc8/ompy/normalizer_nld.py#L679-L680
> 

Ah... here is the error!

> Here we already have a factor of two:
> 
> https://github.com/oslocyclotronlab/ompy/blob/9ac0f5e24b2bd966dcff399cc1c245ae74d9cbc8/ompy/normalizer_nld.py#L681-L682

**Comment by fzeiser** [comment]
Because:
> `rho(Sn) = 2/D0 * 1/(g(J+1/2) + g(J-1/2))`

now with the definition `sum = 1/2 (g(J+1/2) + g(J-1/2))`, this is equivalent to
`rho(Sn) = 2/D0 * 1/(g(J+1/2) + g(J-1/2)) = D0 / sum`

However, the factor of 2 misses for the J=0 case

**Comment by fzeiser** [comment]
Do you change the pull-request or shall I?

**Comment by vetlewi** [comment]
I will fix

**Comment by fzeiser** [comment]
Can you refer to this issue in the docstring of the function (or summarize it)? Thanks!

**Comment by vetlewi** [comment]
> Can you refer to this issue in the docstring of the function (or summarize it)? Thanks!

Done 👍

**Comment by fzeiser** [comment]
Fixed in 852bf7c
